### ISSUE TITLE
download_data.sh fails due to depublication of polyai-models

### ISSUE THREAD

**Issue by entn-at** [alexa/dialoglue#1]
PolyAI has taken down the contents of the https://github.com/PolyAI-LDN/polyai-models repository. Due to this, download_data.sh fails to retrieve the intent data.

**Comment by mihail-amazon** [comment]
Hi @entn-at thanks for pointing this out! We just noticed this change on the original PolyAI repo as well. We'll update the scripts to be functional ASAP.

**Comment by mihail-amazon** [comment]
Just landed a PR that should fix this problem. Let me know if it still doesn't work. Thanks again for pointing this out!
