### ISSUE TITLE
Cannot download pre-trained model

### ISSUE THREAD

**Issue by zqwerty** [alexa/dialoglue#4]
When running
```
python run.py \
        --train_data_path data_utils/dialoglue/hwu/train.csv \
        --val_data_path data_utils/dialoglue/hwu/val.csv \
        --test_data_path data_utils/dialoglue/hwu/test.csv \
        --token_vocab_path bert-base-uncased-vocab.txt \
        --train_batch_size 64 --dropout 0.1 --num_epochs 0 --learning_rate 6e-5 \
        --model_name_or_path convbert-dg --task intent --do_lowercase --max_seq_length 50 --mlm_pre --mlm_during --dump_outputs \
```
there is an error:

```
OSError: Model name 'convbert-dg' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/convbert-dg/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.
```

How to download the checkpoints/pre-trained models stated in the README?

**Comment by mihail-amazon** [comment]
Hi @zqwerty thanks for pointing this out. We're still working on getting our pretrained checkpoints (the `convbert-dg` mentioned) onto a public s3 bucket, which we hope to have done in the next few days. I'll let you know when it's made available.

**Comment by zqwerty** [comment]
Thanks! BTW, could you post your environment (python packages&version) as well?

**Comment by mihail-amazon** [comment]
Yup just opened a PR for it: https://github.com/alexa/dialoglue/pull/6

**Comment by mihail-amazon** [comment]
Hey @zqwerty I've added a link to the checkpoints in our README, which should fix your issue. Let us know if you have any other problems.

**Comment by zqwerty** [comment]
Great!

**Comment by jind11** [comment]
Hi, I saw the link to download the checkpoints, however, I am not familiar with aws commands, so what is the command line to download those checkpoints? Could you provide it or all users need to learn the aws cli commands themselves. Thank you!
