### ISSUE TITLE
How to run TripPy DST using ConvBERT?

### ISSUE THREAD

**Issue by zqwerty** [alexa/dialoglue#5]
As mentioned in the README:

> To train/evaluate the model using our modifications (i.e., MLM pre-training), you can use trippy/DO.example.advanced.

But `trippy/DO.example.advanced` use BERT instead of ConvBERT. I wonder how to reproduce the result of ConvBERT and ConvBERT-DG. Thanks!

**Comment by mihail-amazon** [comment]
As mentioned in https://github.com/alexa/dialoglue/issues/4, we are working as quickly as possible to release these checkpoints so that you can reproduce these results.

**Comment by mihail-amazon** [comment]
Now that the link to the checkpoints are available in the README, this should fix your problem.
