### ISSUE TITLE
Error while using tokenizers

### ISSUE THREAD

**Issue by kapilpathak1112** [alexa/dialoglue#9]
While running the following command:
pip3 install -r requirements.txt

python run.py \
        --train_data_path data_utils/dialoglue/hwu/train.csv \
        --val_data_path data_utils/dialoglue/hwu/val.csv \
        --test_data_path data_utils/dialoglue/hwu/test.csv \
        --token_vocab_path bert-base-uncased-vocab.txt \
        --train_batch_size 64 --dropout 0.1 --num_epochs 100 --learning_rate 6e-5 \
        --model_name_or_path convbert-dg --task intent --do_lowercase --max_seq_length 50 --mlm_pre --mlm_during --dump_outputs \

I get the following error:

Namespace(adam_epsilon=1e-08, device=0, do_lowercase=True, dropout=0.1, dump_outputs=True, grad_accum=2, learning_rate=6e-05, logging_steps=100, max_grad_norm=-1.0, max_seq_length=100, mlm_data_path='', mlm_during=True, mlm_pre=True, model_name_or_path='convbert-dg', num_epochs=100, output_dir='', patience=5, repeat=1, seed=42, task='intent', test_data_path='data_utils/dialoglue/banking/test.csv', token_vocab_path='bert-base-uncased-vocab.txt', train_batch_size=32, train_data_path='data_utils/dialoglue/banking/train.csv', val_data_path='data_utils/dialoglue/banking/val.csv', weight_decay=0.0)
Errors: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Traceback (most recent call last):
  File "run.py", line 566, in <module>
    scores.append(train(args, i))
  File "run.py", line 305, in train
    lowercase=args.do_lowercase)
  File "/home/kapilpathak/py37-venv/lib/python3.7/site-packages/tokenizers/implementations/bert_wordpiece.py", line 30, in __init__
    tokenizer = Tokenizer(WordPiece(vocab_file, unk_token=str(unk_token)))
Exception: Error while initializing WordPiece

The error is consistent even if I change tasks and datasets
Any suggestions?

**Comment by mihail-amazon** [comment]
Did you check to ensure that your virtual env has the tokenizers library? Can you also provide the output of `pip freeze`?

**Comment by kapilpathak1112** [comment]
Hi, the above issue is solved but now I am getting the following error. I am not able to locate 'convbert-dg' model.

Traceback (most recent call last):
  File "/home/kapilpathak/py37-venv/lib/python3.7/site-packages/transformers/configuration_utils.py", line 133, in from_pretrained
    resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)
  File "/home/kapilpathak/py37-venv/lib/python3.7/site-packages/transformers/file_utils.py", line 182, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file convbert-dg not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 566, in <module>
    scores.append(train(args, i))
  File "run.py", line 371, in train
    num_slot_labels=len(train_dataset.slot_label_to_idx))
  File "/home/kapilpathak/dialoglue/bert_models.py", line 60, in __init__
    self.bert_model = BertModel.from_pretrained(model_name_or_path)
  File "/home/kapilpathak/py37-venv/lib/python3.7/site-packages/transformers/modeling_utils.py", line 287, in from_pretrained
    **kwargs
  File "/home/kapilpathak/py37-venv/lib/python3.7/site-packages/transformers/configuration_utils.py", line 145, in from_pretrained
    raise EnvironmentError(msg)
OSError: Model name 'convbert-dg' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed 'convbert-dg' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

I went to the following link but I was not able to locate the models
https://registry.opendata.aws/dialoglue/

**Comment by mihail-amazon** [comment]
The models are in the s3 bucket linked in the registry. You should be able to see them by using:
`aws s3 ls s3://dialoglue/ --no-sign-request`. 

If you install the awscli tool in your env you should be able to run the above to see the available models.

**Comment by kapilpathak1112** [comment]
I could get the following response:

ws s3 ls s3://dialoglue/ --no-sign-request
                           PRE bert-dg/
                           PRE convbert-dg/
                           PRE convbert/
2020-10-10 01:55:54      32357 index.html

But how can we use them? sorry I am completely unaware.
How can we use them on private GPU servers?

I tried the following command:
aws s3 cp s3://dialoglue/convbert-dg .

It gives the following error:
fatal error: Unable to locate credentials

**Comment by mihail-amazon** [comment]
S3 is a cloud-based file store (like Dropbox), so you need to copy the model files to wherever you want to do training. Here there are 3 different model directories. To copy `bert-dg` locally, for example, you can run the following from your server:
```
aws s3 cp --recursive s3://dialoglue/bert-dg bert-dg
```

**Comment by kapilpathak1112** [comment]
It gives the following output:

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument command: Invalid choice, valid choices are:

accessanalyzer                           | acm                                     
acm-pca                                  | alexaforbusiness                        
amplify                                  | apigateway                              
apigatewaymanagementapi                  | apigatewayv2                            
appconfig                                | appflow                                 
application-autoscaling                  | application-insights                    
appmesh                                  | appstream                               
appsync                                  | athena                                  
autoscaling                              | autoscaling-plans                       
backup                                   | batch                                   
braket                                   | budgets                                 
ce                                       | chime                                   
cloud9                                   | clouddirectory                          
cloudformation                           | cloudfront                              
cloudhsm                                 | cloudhsmv2                              
cloudsearch                              | cloudsearchdomain                       
cloudtrail                               | cloudwatch                              
codeartifact                             | codebuild                               
codecommit                               | codeguru-reviewer                       
codeguruprofiler                         | codepipeline                            
codestar                                 | codestar-connections                    
codestar-notifications                   | cognito-identity                        
cognito-idp                              | cognito-sync                            
comprehend                               | comprehendmedical                       
compute-optimizer                        | connect                                 
connectparticipant                       | cur                                     
dataexchange                             | datapipeline                            
datasync                                 | dax                                     
detective                                | devicefarm                              
directconnect                            | discovery                               
dlm                                      | dms                                     
docdb                                    | ds                                      
dynamodb                                 | dynamodbstreams                         
ebs                                      | ec2                                     
ec2-instance-connect                     | ecr                                     
ecs                                      | efs                                     
eks                                      | elastic-inference                       
elasticache                              | elasticbeanstalk                        
elastictranscoder                        | elb                                     
elbv2                                    | emr                                     
es                                       | events                                  
firehose                                 | fms                                     
forecast                                 | forecastquery                           
frauddetector                            | fsx                                     
gamelift                                 | glacier                                 
globalaccelerator                        | glue                                    
greengrass                               | groundstation                           
guardduty                                | health                                  
honeycode                                | iam                                     
identitystore                            | imagebuilder                            
importexport                             | inspector                               
iot                                      | iot-data                                
iot-jobs-data                            | iot1click-devices                       
iot1click-projects                       | iotanalytics                            
iotevents                                | iotevents-data                          
iotsecuretunneling                       | iotsitewise                             
iotthingsgraph                           | ivs                                     
kafka                                    | kendra                                  
kinesis                                  | kinesis-video-archived-media            
kinesis-video-media                      | kinesis-video-signaling                 
kinesisanalytics                         | kinesisanalyticsv2                      
kinesisvideo                             | kms                                     
lakeformation                            | lambda                                  
lex-models                               | lex-runtime                             
license-manager                          | lightsail                               
logs                                     | machinelearning                         
macie                                    | macie2                                  
managedblockchain                        | marketplace-catalog                     
marketplace-entitlement                  | marketplacecommerceanalytics            
mediaconnect                             | mediaconvert                            
medialive                                | mediapackage                            
mediapackage-vod                         | mediastore                              
mediastore-data                          | mediatailor                             
meteringmarketplace                      | mgh                                     
migrationhub-config                      | mobile                                  
mq                                       | mturk                                   
neptune                                  | networkmanager                          
opsworks                                 | opsworkscm                              
organizations                            | outposts                                
personalize                              | personalize-events                      
personalize-runtime                      | pi                                      
pinpoint                                 | pinpoint-email                          
pinpoint-sms-voice                       | polly                                   
pricing                                  | qldb                                    
qldb-session                             | quicksight                              
ram                                      | rds                                     
rds-data                                 | redshift                                
redshift-data                            | rekognition                             
resource-groups                          | resourcegroupstaggingapi                
robomaker                                | route53                                 
route53domains                           | route53resolver                         
s3control                                | s3outposts                              
sagemaker                                | sagemaker-a2i-runtime                   
sagemaker-runtime                        | savingsplans                            
schemas                                  | sdb                                     
secretsmanager                           | securityhub                             
serverlessrepo                           | service-quotas                          
servicecatalog                           | servicediscovery                        
ses                                      | sesv2                                   
shield                                   | signer                                  
sms                                      | snowball                                
sns                                      | sqs                                     
ssm                                      | sso                                     
sso-admin                                | sso-oidc                                
stepfunctions                            | storagegateway                          
sts                                      | support                                 
swf                                      | synthetics                              
textract                                 | timestream-query                        
timestream-write                         | transcribe                              
transfer                                 | translate                               
waf                                      | waf-regional                            
wafv2                                    | workdocs                                
worklink                                 | workmail                                
workmailmessageflow                      | workspaces                              
xray                                     | s3api                                   
s3                                       | ddb                                     
configure                                | deploy                                  
configservice                            | opsworks-cm                             
history                                  | cli-dev                                 
help

**Comment by mihail-amazon** [comment]
I updated the command. Otherwise, I encourage you to read the documentation on using the `awscli` tool: https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html

**Comment by Kapil-Pathak** [comment]
It's giving following output:

fatal error: Unable to locate credentials
Please help
